### ISSUE TITLE
Unable to locate ETFrameworkFault.xsd file

### ISSUE THREAD

**Issue by petermcstayhallolson** [salesforce-marketingcloud/FuelSDK-Java#45]
@amagar088 

I've recently updated my project to use Java 8 and have since been running into issues with Fuel SDK.
Has there been any significant changes to how ET and Fuel SDK is to be implemented?
The following exception is thrown when I use either version 1.0.3 or 1.1.0 with CXF version 2.7.16 or 3.1.0.
I have also attempted to add the required file to my project's resource folder.

javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:347)
	at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:336)
	at javax.xml.ws.Service.getPort(Service.java:119)
	at com.exacttarget.fuelsdk.internal.PartnerAPI.getSoap(PartnerAPI.java:63)
	at com.exacttarget.fuelsdk.ETSoapConnection.<init>(ETSoapConnection.java:89)
	at com.exacttarget.fuelsdk.ETSoapConnection.<init>(ETSoapConnection.java:178)
	at com.exacttarget.fuelsdk.ETClient.<init>(ETClient.java:158)
	at com.olson.bostonpizza.service.messagequeue.exacttarget.ExactTargetSubscriberConsumer.registerNewUser(ExactTargetSubscriberConsumer.java:70)
	at com.olson.bostonpizza.service.messagequeue.exacttarget.ExactTargetRegisterSubscriberConsumer.handleDelivery(ExactTargetRegisterSubscriberConsumer.java:128)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.create(WSDLServiceFactory.java:183)
	at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL(ReflectionServiceFactoryBean.java:428)
	at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:548)
	at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:265)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:215)
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:102)
	at org.apache.cxf.frontend.ClientFactoryBean.create(ClientFactoryBean.java:91)
	at org.apache.cxf.frontend.ClientProxyFactoryBean.create(ClientProxyFactoryBean.java:157)
	at org.apache.cxf.jaxws.JaxWsProxyFactoryBean.create(JaxWsProxyFactoryBean.java:142)
	at org.apache.cxf.jaxws.ServiceImpl.createPort(ServiceImpl.java:478)
	at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:345)
	... 13 more
Caused by: org.apache.ws.commons.schema.XmlSchemaException: Unable to locate imported document at 'https://webservice.exacttarget.com/ETFrameworkFault.xsd', relative to 'jar:file:/Users/37311/.m2/repository/com/exacttarget/fuelsdk/1.1.0/fuelsdk-1.1.0.jar!/etframework.wsdl#types1'.
	at org.apache.cxf.catalog.CatalogXmlSchemaURIResolver.resolveEntity(CatalogXmlSchemaURIResolver.java:76)
	at org.apache.ws.commons.schema.SchemaBuilder.resolveXmlSchema(SchemaBuilder.java:684)
	at org.apache.ws.commons.schema.SchemaBuilder.handleImport(SchemaBuilder.java:538)
	at org.apache.ws.commons.schema.SchemaBuilder.handleSchemaElementChild(SchemaBuilder.java:1513)
	at org.apache.ws.commons.schema.SchemaBuilder.handleXmlSchemaElement(SchemaBuilder.java:659)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:540)
	at org.apache.cxf.common.xmlschema.SchemaCollection.read(SchemaCollection.java:129)
	at org.apache.cxf.wsdl11.SchemaUtil.extractSchema(SchemaUtil.java:140)
	at org.apache.cxf.wsdl11.SchemaUtil.getSchemas(SchemaUtil.java:73)
	at org.apache.cxf.wsdl11.SchemaUtil.getSchemas(SchemaUtil.java:65)
	at org.apache.cxf.wsdl11.SchemaUtil.getSchemas(SchemaUtil.java:60)
	at org.apache.cxf.wsdl11.WSDLServiceBuilder.getSchemas(WSDLServiceBuilder.java:372)
	at org.apache.cxf.wsdl11.WSDLServiceBuilder.buildServices(WSDLServiceBuilder.java:339)
	at org.apache.cxf.wsdl11.WSDLServiceBuilder.buildServices(WSDLServiceBuilder.java:203)
	at org.apache.cxf.wsdl11.WSDLServiceFactory.create(WSDLServiceFactory.java:175)
	... 23 more

**Comment by sud201449** [comment]
HI @petermcstayhallolson ,
  I am getting same exception .. is there any work around for this?

**Comment by sharif26** [comment]
Try to use our new version 1.2.2 as mentioned in readme file and let us know.
Thanks.

**Comment by subala-murthy** [comment]
Hi sharif26, I have been getting the same exception for last 4 days(the code worked fine before) and I have updated the exacttarget version to 1.2.2 like you have suggested. still no use.... 
Any other help/suggestion will be much appreciated.

**Comment by subala-murthy** [comment]
It was my mistake that i added the code in powermock test, the PowerMockRunner breaks the  javax.net.ssl.SSLContext and the exception is thrown.
Works fine when i run it in normal Junit runner rather than PowerMock's own.

**Comment by sud201449** [comment]
My issue was also related to SSL , i have added certificate for webservice.exacttarget.com in my jvm trust store to solve the issue

**Comment by shashishekhard** [comment]
I am also getting the same issue as above. I am using version 1.2.2. It worked for me for last 2 days but now I am getting the above exceptions. I added auth.exacttargetapis.com certificate. Do I need to add any other certificate?
