### ISSUE TITLE
NullPointerException in login

### ISSUE THREAD

**Issue by hlms** [salesforce-marketingcloud/FuelSDK-Java#51]
I am using fuel-java-1.0.1. Using the following code for login:
```
ETConfiguration configuration = new ETConfiguration();
configuration.set("clientId", "my-client-id");
configuration.set("clientSecret", "my-client-secret");
ETClient client = new ETClient(configuration);
```

Intermittently, it fails with the following exception:

```
Caused by: java.lang.NullPointerException
    at com.exacttarget.fuelsdk.ETClient.<init>(ETClient.java:131) ~[fuel-java-1.0.1.jar:?]
```
How to resolve the issue?

Will the latest version help?

cross-posted: http://salesforce.stackexchange.com/questions/143160/fuel-sdk-java-nullpointerexception-in-login

**Comment by robertfarkas-epam** [comment]
Adding soapEndpoint (https://webservice.exacttarget.com/Service.asmx) helped to go further a bit but next execution resulted this exception:

java.lang.NullPointerException
        at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85)
        at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:218)
        at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:161)
        at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:129)
        at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82)
        at javax.xml.ws.Service.<init>(Service.java:77)
        at com.exacttarget.fuelsdk.internal.PartnerAPI.<init>(PartnerAPI.java:49)
        at com.exacttarget.fuelsdk.ETSoapConnection.<init>(ETSoapConnection.java:101)
        at com.exacttarget.fuelsdk.ETSoapConnection.<init>(ETSoapConnection.java:211)
        at com.exacttarget.fuelsdk.ETClient.<init>(ETClient.java:169)

This is because in ServiceImpl in line 153: 
 Definition e = ((WSDLManager)this.bus.getExtension(WSDLManager.class)).getDefinition(this.wsdlURL);

the ExtensionManagerBus contains the WSDLManager in missingExtensions.
I have no idea how to solve the issue.

**Comment by sharif26** [comment]
soapEndpoint is not mandatory, but authEndpoint is. so you need to set that as well if you use ETConfiguration:
`configuration.set("authEndpoint", "https://auth.exacttargetapis.com");`
Please check out our fuelsdk.properties.template file, we encourage to rename it to fuelsdk.properties and set clientId and clientSecret for ease of use.

**Comment by robertfarkas-epam** [comment]
Thanks for your reply. :)
Unfortunately defining authEndpoint does not make any difference because I get the same error.

**Comment by kociepa** [comment]
[This](https://stackoverflow.com/a/9069435/4682359) works for me

**Comment by vvelayutham** [comment]
@robertfarkas-epam i am also hitting the same problem. It is working in my local but when i move the jar to my server and run, am seeing this issue. Were you able to solve the problem. i know its kinda old thread but any help is appreciated

**Comment by oanguin** [comment]
I am also having this issue. Was anyone able to resolve it.

**Comment by ayush9** [comment]
I am also having this issue. Was anyone able to resolve it?
