### ISSUE TITLE
ETClickEventTest fails

### ISSUE THREAD

**Issue by ddRoberto** [salesforce-marketingcloud/FuelSDK-Java#88]
ETClickEventTest fails with this error when I execute it

```
-------------------------------------------------------------------------------
Test set: com.exacttarget.fuelsdk.ETClickEventTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.703 sec <<< FAILURE!
getAllClicks(com.exacttarget.fuelsdk.ETClickEventTest)  Time elapsed: 1.529 sec  <<< ERROR!
com.exacttarget.fuelsdk.ETSdkException: error invoking retrieve method for type class com.exacttarget.fuelsdk.ETClickEvent
	at com.exacttarget.fuelsdk.ETClient.retrieve(ETClient.java:514)
	at com.exacttarget.fuelsdk.ETClient.retrieve(ETClient.java:460)
	at com.exacttarget.fuelsdk.ETClickEventTest.getAllClicks(ETClickEventTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exacttarget.fuelsdk.ETClient.retrieve(ETClient.java:507)
	... 35 more
Caused by: com.exacttarget.fuelsdk.ETSdkException: could not get property "urlid" of object com.exacttarget.fuelsdk.internal.ClickEvent@7ee12d58[...]
	at com.exacttarget.fuelsdk.ETSoapObject.fromInternal(ETSoapObject.java:1045)
	at com.exacttarget.fuelsdk.ETSoapObject.retrieve(ETSoapObject.java:390)
	at com.exacttarget.fuelsdk.ETSoapObject.retrieve(ETSoapObject.java:173)
	at com.exacttarget.fuelsdk.ETSoapObject.retrieve(ETSoapObject.java:149)
	... 40 more
Caused by: java.lang.NoSuchMethodException: Unknown property 'urlid' on class 'class com.exacttarget.fuelsdk.internal.ClickEvent'
	at org.apache.commons.beanutils.PropertyUtilsBean.getSimpleProperty(PropertyUtilsBean.java:1269)
	at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:808)
	at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:884)
	at org.apache.commons.beanutils.PropertyUtils.getProperty(PropertyUtils.java:464)
	at com.exacttarget.fuelsdk.ETSoapObject.fromInternal(ETSoapObject.java:1042)
	... 43 more

```
I have tested SOAP service and it worked

FuelSDK-Java version 1.2.2

**Comment by vj-cyntexa** [comment]
@ddRoberto Did you find any solution for this?

**Comment by vj-cyntexa** [comment]
@ddRoberto I am facing the issue in actually fetching the Click Event. `ETClickEvent`
